S02 us14 admin activities edit
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #143
Opened 2021-04-24 16:01 UTC by eguesbaya

2021-04-26 07:30 UTC, maxime-guichard approved these changes

2021-04-27 07:02 UTC, glochlainn approved these changes

2021-04-27 07:13 UTC, sblondeau requested changes
j'ai index et edit dans la meme US là ? à redecouper pour avoir que le edit, qui correspond à ta US

2021-04-27 07:13 UTC, sblondeau commented on src/Controller/AdminActivityController.php
> +    public const DAYS = ['test1', 'test2'];
??

2021-04-27 07:13 UTC, sblondeau commented on src/Controller/AdminActivityController.php
> +                //$activityManager = new ActivityManager();
pas de code commenté

2021-04-27 07:13 UTC, sblondeau commented on src/View/Item/edit.html.twig
>  {% extends 'layout.html.twig' %}
attention tu es dans Item et non dans un dossier approprié, Admin/Activity je pense ?

2021-04-27 09:10 UTC, eguesbaya commented on src/Controller/AdminActivityController.php
> +    public const DAYS = ['test1', 'test2'];
Oups, c'est supprimé

2021-04-27 09:15 UTC, eguesbaya commented on src/Controller/AdminActivityController.php
> +                //$activityManager = new ActivityManager();
supprimé

2021-04-27 09:17 UTC, eguesbaya commented on src/View/Item/edit.html.twig
>  {% extends 'layout.html.twig' %}
Tu as commenté sur le fichier Item/edit donc je pense que c'est normal? A priori ma méthode edit de AdminActivityController renvoie bien vers Admin/Activity/edit.html.twig

2021-04-27 09:21 UTC, gerseystelmach approved these changes

2021-04-27 09:39 UTC, maxime-guichard submitted a review, later dismissed

2021-04-27 14:53 UTC, eguesbaya commented on src/View/Item/edit.html.twig
>  {% extends 'layout.html.twig' %}
c'est résolu

2021-04-27 15:22 UTC, gerseystelmach approved these changes

2021-04-27 15:23 UTC, maxime-guichard approved these changes

2021-04-28 07:44 UTC, sblondeau approved these changes

2021-04-28 07:44 UTC, merged