S03US19 - Events View Page
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #150
Opened 2021-04-28 13:37 UTC by gerseystelmach

2021-04-28 13:39 UTC, maxime-guichard submitted a review, later dismissed

2021-04-28 13:39 UTC, eguesbaya submitted a review, later dismissed

2021-04-28 15:11 UTC, sblondeau requested changes
images trop grosses

2021-04-28 15:11 UTC, sblondeau commented on public/assets/css/event.css
> +    background-color: #fff;
couleur en variable CSS

2021-04-28 15:11 UTC, sblondeau commented on src/View/Home/event.html.twig
> +						<div class="flip-card-back">
ces informations doivent provenir d'une table en base de donées

2021-04-30 07:41 UTC, eguesbaya approved these changes

2021-04-30 08:04 UTC, closed without merging