S03 us20 display activities
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #151
Opened 2021-04-28 13:41 UTC by eguesbaya

2021-04-28 13:52 UTC, gerseystelmach submitted a review, later dismissed

2021-04-28 14:58 UTC, maxime-guichard approved these changes

2021-04-28 15:01 UTC, gerseystelmach approved these changes

2021-04-28 15:14 UTC, sblondeau requested changes

2021-04-28 15:14 UTC, sblondeau commented on public/assets/css/activity.css
> +    color: white;
couleur CSS

2021-04-29 10:20 UTC, eguesbaya commented on public/assets/css/activity.css
> +    color: white;
Remplacé par une variable

2021-04-29 15:17 UTC, sblondeau requested changes

2021-04-29 15:17 UTC, sblondeau commented on src/Controller/ActivityController.php
> +    public const DAYS = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi'];
tu as déjà cette constante dans ton ActivityManager normalement maintenant, donc il faut l'utiliser et pas recréer encore la constante

2021-04-29 15:17 UTC, sblondeau commented on src/View/Home/activity.html.twig
> +            {% for day in constant('App\\Controller\\AdminActivityController::DAYS' ) %}
ActityManager je crois

2021-04-29 20:25 UTC, eguesbaya commented on src/Controller/ActivityController.php
> +    public const DAYS = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi'];
Supprimé

2021-04-29 20:28 UTC, eguesbaya commented on src/View/Home/activity.html.twig
> +            {% for day in constant('App\\Controller\\AdminActivityController::DAYS' ) %}
Ca y est c'est réglé

2021-04-30 07:23 UTC, glochlainn approved these changes

2021-04-30 08:04 UTC, maxime-guichard approved these changes

2021-04-30 08:24 UTC, sblondeau approved these changes

2021-04-30 08:24 UTC, merged