S03US27_aboutTimeline
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #157
Opened 2021-04-28 14:22 UTC by glochlainn

2021-04-28 14:28 UTC, maxime-guichard submitted a review, later dismissed

2021-04-28 14:58 UTC, maxime-guichard submitted a review, later dismissed

2021-04-28 15:01 UTC, gerseystelmach submitted a review, later dismissed

2021-04-28 15:18 UTC, sblondeau requested changes

2021-04-28 15:18 UTC, sblondeau commented on public/assets/css/about.css
> +    background: #c6c6c6;
couleur variable CSS

2021-04-28 15:18 UTC, sblondeau commented on public/assets/css/about.css
> +    background: #fff;
couleur variable CSS

2021-04-28 15:18 UTC, sblondeau commented on public/assets/css/about.css
> +    background: #fff;
je te laisse le modif partout ou necessaire

2021-04-28 15:18 UTC, sblondeau commented on public/assets/css/about.css
> +   ---------TIMELINE----------
j'imagine vu la longueur que c'est un bout de CSS que tu as récupéré pour la timeline ?
Je ne vais pas t'embêter trop avec la partie media queries du coup meme si la plupart serait gérable via bootstrap.
Par contre, gère les couleurs en variable au moins

2021-04-30 07:24 UTC, maxime-guichard submitted a review, later dismissed

2021-04-30 07:39 UTC, closed without merging