S3 us17 create tables: photo and album
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #169
Opened 2021-04-29 08:27 UTC by eguesbaya

Created a Photo and Album tables (linked)

2021-04-30 08:15 UTC, gerseystelmach approved these changes

2021-05-01 12:49 UTC, maxime-guichard submitted a review, later dismissed

2021-05-02 08:55 UTC, maxime-guichard submitted a review, later dismissed

2021-05-03 07:43 UTC, glochlainn approved these changes

2021-05-03 07:45 UTC, glochlainn requested changes

2021-05-03 07:45 UTC, glochlainn commented on temps_des_loisirs.sql
> -LOCK TABLES `information` WRITE;
Tu supprimes la table information et ne la recréé nulle part ailleurs, à corriger du coup

2021-05-03 08:41 UTC, eguesbaya commented on temps_des_loisirs.sql
> -LOCK TABLES `information` WRITE;
table ré-introduite

2021-05-04 07:18 UTC, glochlainn approved these changes

2021-05-04 11:48 UTC, maxime-guichard approved these changes

2021-05-04 13:59 UTC, sblondeau approved these changes

2021-05-04 13:59 UTC, merged