S03US29 Footer (Footer creation. Insert into layout as a component)
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #201
Opened 2021-04-30 15:34 UTC by gerseystelmach

2021-05-01 12:47 UTC, maxime-guichard submitted a review, later dismissed

2021-05-03 07:42 UTC, glochlainn submitted a review, later dismissed

2021-05-03 08:09 UTC, sblondeau requested changes

2021-05-03 08:09 UTC, sblondeau commented on src/View/Components/_footer.html.twig
> +	<div class="text-center p-3 text-light footerCopyright" style="background-color: rgba(0, 0, 0, 0.2);">
pas de style en inline, fait ça dans ton fichier CSS

2021-05-04 07:17 UTC, glochlainn approved these changes

2021-05-04 11:47 UTC, maxime-guichard approved these changes

2021-05-04 13:57 UTC, sblondeau approved these changes

2021-05-04 13:57 UTC, merged