Created HomeController and HomeManager
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #203
Opened 2021-05-01 17:39 UTC by eguesbaya

HomeManager contains SelectInfo method only for now.

2021-05-02 08:54 UTC, maxime-guichard approved these changes

2021-05-03 07:41 UTC, glochlainn approved these changes

2021-05-03 09:05 UTC, sblondeau requested changes

2021-05-03 09:05 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $information = $homeManager->selectInfo('date');
non si tu as plusieurs tables il te faut plusieurs Manager

2021-05-04 14:01 UTC, closed without merging