S4 us32 accueil entete
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #204
Opened 2021-05-01 18:17 UTC by eguesbaya

2021-05-02 08:53 UTC, maxime-guichard approved these changes

2021-05-03 07:41 UTC, glochlainn approved these changes

2021-05-03 10:00 UTC, sblondeau requested changes

2021-05-03 10:00 UTC, sblondeau commented on public/assets/css/home.css
> +    background-image: url(https://picsum.photos/200/300);
mets une vrai images que tu auras dans ton assets/images, utilise pas du picsum ici

2021-05-04 14:01 UTC, closed without merging