S03US11_contact ajout du backend pour le contact
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #205
Opened 2021-05-03 08:01 UTC by maxime-guichard

2021-05-04 15:54 UTC, glochlainn approved these changes

2021-05-04 17:12 UTC, glochlainn approved these changes

2021-05-05 07:17 UTC, eguesbaya approved these changes

2021-05-05 07:27 UTC, sblondeau requested changes

2021-05-05 07:27 UTC, sblondeau commented on src/Controller/ContactController.php
> +        $titles = ['M' => 'Monsieur', 'Mme' => 'Madame', 'Melle' => 'Mademoiselle'];
utilise plutot une constante ici, ça te permet de réutiliser l'info partout (dans ta validation, dans ton Twig, etc)

2021-05-05 07:27 UTC, sblondeau commented on public/assets/css/thanks.css
> +@import 'style.css';
idem

2021-05-05 07:27 UTC, sblondeau commented on public/assets/css/contact.css
> +@import 'style.css';
non tu ne doits pas réimporter tes feuilles de style ici, celle-ci sont déjà chargées dans tes layouts

2021-05-05 07:27 UTC, sblondeau commented on public/assets/css/contact.css
> +#maCarte {
fais une classe plutot que d'utiliser un id

2021-05-05 07:27 UTC, sblondeau commented on src/Controller/ContactController.php
> +            if (!in_array($data['title'], $titles)) {
self:TITLES

2021-05-05 07:27 UTC, sblondeau commented on src/View/Contact/_form.html.twig
> +				{% for title in titles %}
tu peux laisser comme ça mais idéalemnet tu pourrais réutiliser la constante TITLE ici

2021-05-05 08:54 UTC, glochlainn submitted a review, later dismissed

2021-05-05 08:56 UTC, eguesbaya approved these changes

2021-05-05 09:32 UTC, sblondeau requested changes

2021-05-05 09:32 UTC, sblondeau commented on src/View/Contact/thanks.html.twig
> +        <br/>
pas de br pour faire des espacements verticaux. Utiliser du margin en CSS

2021-05-05 09:32 UTC, sblondeau commented on src/View/Contact/index.html.twig
> +		<br/>
pas de br pour faire des espacements verticaux. Utiliser du margin en CSS

2021-05-05 09:32 UTC, sblondeau commented on public/assets/css/contact.css
> +@import 'admin.css';
reste admin.css qui ne devrait pas etre importé

2021-05-05 09:32 UTC, sblondeau commented on public/assets/css/thanks.css
> +@import 'admin.css';
idem

2021-05-05 10:13 UTC, gerseystelmach approved these changes

2021-05-05 10:15 UTC, glochlainn approved these changes

2021-05-05 10:16 UTC, sblondeau approved these changes

2021-05-05 10:16 UTC, merged