S03US32 Page d'Accueil complète
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #208
Opened 2021-05-04 14:36 UTC by gerseystelmach

2021-05-04 15:48 UTC, maxime-guichard submitted a review, later dismissed

2021-05-04 15:54 UTC, glochlainn approved these changes

2021-05-04 16:12 UTC, sblondeau requested changes
image trop grosse !

2021-05-05 08:39 UTC, maxime-guichard approved these changes

2021-05-05 08:39 UTC, eguesbaya submitted a review, later dismissed

2021-05-05 08:52 UTC, sblondeau reviewed
l'image doit faire moins de 200ko

2021-05-05 08:52 UTC, sblondeau commented on public/assets/css/home.css
> +    /* font-size: 8vh; */
code commenté

2021-05-05 08:52 UTC, sblondeau commented on public/assets/css/home.css
> +    color: white;
couleur varable

2021-05-05 08:52 UTC, sblondeau commented on public/assets/css/home.css
> +.informationSection::-webkit-scrollbar-track,
oublie tous les webkit-scrollbar-track, ce n'est pas standard et ne fonctionne que sur chrome

2021-05-05 08:52 UTC, sblondeau requested changes
CSS à modifier

2021-05-05 09:57 UTC, eguesbaya approved these changes

2021-05-05 09:58 UTC, maxime-guichard approved these changes

2021-05-05 10:11 UTC, sblondeau approved these changes

2021-05-05 10:11 UTC, merged