Merge S01US04_adminCA to dev
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #31
Opened 2021-04-15 09:52 UTC by glochlainn

final version of board page

2021-04-15 10:02 UTC, eguesbaya submitted a review, later dismissed
All good!

2021-04-15 10:04 UTC, maxime-guichard submitted a review, later dismissed

2021-04-15 10:06 UTC, gerseystelmach approved these changes
All the modifications were made in accordance to the US assigned to Lochlainn. The DB was created in accordance to the others US. Approved.

2021-04-15 11:46 UTC, sblondeau requested changes

2021-04-15 11:46 UTC, sblondeau commented on public/assets/css/style.css
> +.primary-btn {
trop compliqué pour surchargé le css de ton bouton. 
y a plusieurs solution pour faire ça mais faut mieux surcharger la class btn-primary

un exemple de solution simple, à adapter à tes besoins (mais je vous ferais peut etre utiliser autre chose de plus complet après)
.btn-primary, .btn-primary:hover, .btn-primary:active, .btn-primary:focus {
    background-color: var(--primary);
    border-color: var(--primary);
}
.btn:hover {
    filter: brightness(110%);
}
.btn:active {
    filter: brightness(90%);
}

2021-04-15 11:46 UTC, sblondeau commented on public/assets/css/style.css
> +.delete {
idem là tu répète trop de code, je pense que tu peux surcharger btn-danger non ?

2021-04-15 13:25 UTC, gerseystelmach submitted a review, later dismissed
It seems to me that all changes fit what Sylvain requested.

2021-04-15 14:28 UTC, eguesbaya approved these changes
All good

2021-04-15 15:24 UTC, sblondeau requested changes

2021-04-15 15:24 UTC, sblondeau commented on src/View/Admin/board_index.html.twig
> +							<h5 class="card-title">{{ boardMember.firstname }}
hierarchisation des titres
tu devrais avoir un h2 ou h3 (ou un div si tu ne veux pas utiliser de hX  mais là on passe de h1 à h5

2021-04-16 08:45 UTC, maxime-guichard approved these changes

2021-04-16 08:46 UTC, maxime-guichard approved these changes

2021-04-16 08:46 UTC, maxime-guichard approved these changes

2021-04-16 08:47 UTC, maxime-guichard approved these changes

2021-04-16 08:48 UTC, maxime-guichard approved these changes

2021-04-16 13:30 UTC, eguesbaya submitted a review, later dismissed

2021-04-16 13:31 UTC, maxime-guichard approved these changes

2021-04-16 13:31 UTC, maxime-guichard approved these changes

2021-04-16 13:32 UTC, maxime-guichard approved these changes

2021-04-16 13:32 UTC, maxime-guichard submitted a review, later dismissed

2021-04-16 13:59 UTC, sblondeau requested changes

2021-04-16 13:59 UTC, sblondeau commented on public/assets/css/board.css
> +        font-size: 1.5em;
mis à part la font-size (et encore je pense qu'on peut faire autrement) tout le reste de la media query est gérable avec les classes bootstrap
- https://getbootstrap.com/docs/5.0/utilities/flex/#direction
-  https://getbootstrap.com/docs/5.0/utilities/spacing/#notation

2021-04-16 13:59 UTC, sblondeau commented on src/View/layout.html.twig
> +		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" cross
attention le CSS de bootstrap doit etre appelé AVANT le style.css si tu veux pouvoir surcharger bootstrap ;-)

2021-04-16 15:32 UTC, eguesbaya approved these changes
Bravo tu as enlevé tout le CSS!

2021-04-16 15:33 UTC, maxime-guichard approved these changes

2021-04-19 07:07 UTC, sblondeau approved these changes

2021-04-19 07:07 UTC, merged