S01 us02 admin activities
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #39
Opened 2021-04-15 11:41 UTC by eguesbaya

Structure de la partie listant toutes les activités dans la vue admin

2021-04-15 14:30 UTC, gerseystelmach approved these changes

2021-04-19 11:40 UTC, glochlainn requested changes
Pas de code commenté (AdminActivityController.php)
Ton fichier admin_activities est vide, supprime le ?
Tes imports de Bootstrap dans ton index.html.twig, mets les directement dans le layout, c'est plus pratique que de les appeler à chaque fois

2021-04-19 13:28 UTC, eguesbaya commented
> Pas de code commenté (AdminActivityController.php)
> Ton fichier admin_activities.css est vide, supprime le ?
> Tes imports de Bootstrap dans ton index.html.twig, mets les directement dans le layout, c'est plus pratique que de les appeler à chaque fois

All done

2021-04-19 13:29 UTC, glochlainn approved these changes

2021-04-19 14:13 UTC, gerseystelmach approved these changes

2021-04-20 14:38 UTC, sblondeau requested changes

2021-04-20 14:38 UTC, sblondeau commented on src/Model/AdminActivityManager.php
> +    public const TABLE = 'activities';
activity (singulier les noms de table)

2021-04-20 14:38 UTC, sblondeau commented on src/View/Admin/Activity/index.html.twig
> +                    <h5 class="card-title">{{ activity.name }}</h5>
attention à la hiérarchie des titres, h1 suivi d'un h2 pas d'un h5

2021-04-20 15:06 UTC, eguesbaya commented on src/View/Admin/Activity/index.html.twig
> +                    <h5 class="card-title">{{ activity.name }}</h5>
Fixed

2021-04-20 15:07 UTC, eguesbaya commented on src/Model/AdminActivityManager.php
> +    public const TABLE = 'activities';
Fixed

2021-04-20 15:12 UTC, maxime-guichard submitted a review, later dismissed

2021-04-21 07:49 UTC, glochlainn approved these changes

2021-04-21 08:34 UTC, sblondeau requested changes

2021-04-21 08:34 UTC, sblondeau commented on src/Model/AdminActivityManager.php
> +class AdminActivityManager extends AbstractManager
non comme je le disais en livecoding, tu fais un AdminActivityController mais tu travaille tjs avec le ActivityManager donc pas besoin de faire un AdminActivityManager

2021-04-21 08:34 UTC, sblondeau commented on .gitignore
> +temps_des_loisirs.sql
ne mets pas ça dans le gitignore sinon vous pourrez pas vous partager les infos

2021-04-21 09:10 UTC, eguesbaya commented on .gitignore
> +temps_des_loisirs.sql
Fixed

2021-04-21 09:11 UTC, eguesbaya commented on src/Model/AdminActivityManager.php
> +class AdminActivityManager extends AbstractManager
En effet, c'est réparé

2021-04-21 10:05 UTC, gerseystelmach approved these changes

2021-04-21 14:11 UTC, sblondeau requested changes
hum, tu es sure que tu as bien commit tes modifs ? car je vois tjs le fichier dans .gitignore et j'ai tjs le AdminActivityManager ;-)

2021-04-21 15:27 UTC, glochlainn approved these changes

2021-04-21 20:30 UTC, maxime-guichard approved these changes

2021-04-22 07:12 UTC, sblondeau approved these changes

2021-04-22 07:12 UTC, merged