Création de la navbar admin
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #40
Opened 2021-04-15 12:02 UTC by maxime-guichard

2021-04-15 14:31 UTC, eguesbaya approved these changes
Looks good to me

2021-04-15 14:35 UTC, gerseystelmach submitted a review, later dismissed
The structure seems ok to me, however we still have to review the style for the navbar.

2021-04-19 14:05 UTC, eguesbaya requested changes
Je n'ai pas testé si ça marche, mais il y a encore le "dark" dans ta navbar, à mon avis ça doit masquer ton background.

2021-04-20 15:03 UTC, glochlainn submitted a review, later dismissed

2021-04-20 15:09 UTC, eguesbaya approved these changes
Looking good

2021-04-21 14:15 UTC, sblondeau requested changes
j'ai 2 fichiers favicon (.ico et .png, plus un fichier logo.resized (peut-etre le renommer en juste logo ça serait plus propre)

2021-04-21 14:15 UTC, sblondeau commented on public/assets/css/navbar.css
> +    border: none !important;
idem

2021-04-21 14:15 UTC, sblondeau commented on src/Model/BoardManager.php
> +    public const TABLE = 'board';
ne correspond pas à la US qui est juste sur la navbar admin

2021-04-21 14:15 UTC, sblondeau commented on src/View/Home/index.html.twig
> +<link rel="stylesheet" href='/assets/css/?.css'>
un soucis dans le nom du fichier css non ?

2021-04-21 14:15 UTC, sblondeau commented on src/View/layout.html.twig
> +			{% include 'Components/_navbarAdmin.html.twig' %}
attention là tu mets la navbar_admin par défaut sur toutes les pages en faisant ça, plutot mettre la navbar visiteur ? 
et vous pourriez faire aussi un layout_admin propre à la partie admin si nécessaire

2021-04-21 14:18 UTC, glochlainn commented on src/Model/BoardManager.php
> +    public const TABLE = 'board';
c'est hérité de la branche dev

2021-04-21 15:24 UTC, glochlainn approved these changes

2021-04-21 15:29 UTC, eguesbaya approved these changes
good

2021-04-22 07:14 UTC, sblondeau approved these changes

2021-04-22 07:14 UTC, merged