S01 us09 admin home
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #41
Opened 2021-04-15 15:12 UTC by eguesbaya

2021-04-16 13:52 UTC, maxime-guichard approved these changes

2021-04-19 11:33 UTC, glochlainn submitted a review, later dismissed

2021-04-20 15:11 UTC, maxime-guichard submitted a review, later dismissed

2021-04-21 14:19 UTC, sblondeau requested changes

2021-04-21 14:19 UTC, sblondeau commented on src/Controller/AdminController.php
> +    public function delete(): string
pas de code commenté dans les PR !

2021-04-21 14:19 UTC, sblondeau commented on src/Model/AdminManager.php
> +    public const TABLE = 'activities';
pourquoi un AdminManager avec une table activities ? 
là ta US tu n'as pas besoin d'aller chercher des infos en BDD, c'est juste une page d'acceuil statique non ? 
donc pas de manager à créer ou à utiliser

2021-04-21 14:19 UTC, sblondeau commented on src/View/Admin/home.html.twig
> +            <p>Ajouter, éditer et suprimer les alertes affichées sur la page d’accueil</p>
sup**p**rimer

2021-04-21 14:19 UTC, sblondeau commented on src/View/Admin/home.html.twig
> +            <p>Ajouter, éditer et suprimer des informations sur le conseil d’administration</p>
sup**p**rimer

2021-04-21 14:19 UTC, sblondeau commented on src/View/Admin/home.html.twig
> +            <p>Ajouter, éditer et suprimer vos activités</p>
sup**p**rimer

2021-04-21 16:10 UTC, eguesbaya commented on src/View/Admin/home.html.twig
> +            <p>Ajouter, éditer et suprimer les alertes affichées sur la page d’accueil</p>
Je ne comprends pas... Supprimer la gestion des informations?

2021-04-21 16:10 UTC, eguesbaya commented on src/View/Admin/home.html.twig
> +            <p>Ajouter, éditer et suprimer des informations sur le conseil d’administration</p>
Pareil...

2021-04-21 16:11 UTC, eguesbaya commented on src/View/Admin/home.html.twig
> +            <p>Ajouter, éditer et suprimer vos activités</p>
Supprimer quoi et pourquoi?

2021-04-21 19:43 UTC, eguesbaya commented on src/Controller/AdminController.php
> +    public function delete(): string
Fixed

2021-04-22 07:20 UTC, sblondeau requested changes

2021-04-22 07:20 UTC, sblondeau commented on public/assets/css/admin_activities.css
> +.btn{
me parait pas logique de réduire la taille des btn, en tout cas pas spécifiquement sur une seule page admin activity

2021-04-22 07:20 UTC, sblondeau commented on public/assets/css/admin_home.css
> +.btn{
ce code CSS est le meme (ou presque) que le fichier css précédent, donc y a des choses à refactoriser là

2021-04-22 07:20 UTC, sblondeau commented on src/Model/ActivityManager.php
> +class AdminManager extends AbstractManager
attention ta classe s'appelle AdminManager et le fichier ActivityManager

2021-04-22 07:20 UTC, sblondeau commented on src/View/Admin/home.html.twig
> +            <p>Ajouter, éditer et suprimer des informations sur le conseil d’administration</p>
non y a une type, il manque un P !!!

2021-04-22 07:58 UTC, eguesbaya commented on src/Model/AdminManager.php
> +    public const TABLE = 'activities';
Résolu

2021-04-22 08:03 UTC, eguesbaya commented on src/Model/ActivityManager.php
> +class AdminManager extends AbstractManager
résolu

2021-04-22 08:03 UTC, eguesbaya commented on src/View/Admin/home.html.twig
> +            <p>Ajouter, éditer et suprimer vos activités</p>
J'ai compris! c'est résolu :D

2021-04-22 08:16 UTC, eguesbaya commented on public/assets/css/admin_home.css
> +.btn{
fichiers css retirés

2021-04-22 08:16 UTC, eguesbaya commented on public/assets/css/admin_activities.css
> +.btn{
css retiré

2021-04-22 08:27 UTC, maxime-guichard approved these changes

2021-04-22 08:28 UTC, gerseystelmach approved these changes

2021-04-22 08:31 UTC, glochlainn approved these changes

2021-04-22 09:01 UTC, sblondeau approved these changes

2021-04-22 09:01 UTC, merged