S01US06_deleteAdminCA to dev
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #74
Opened 2021-04-19 14:52 UTC by glochlainn

all of the feature to delete a CA member

2021-04-20 15:10 UTC, eguesbaya approved these changes
Approved

2021-04-20 15:13 UTC, maxime-guichard submitted a review, later dismissed

2021-04-21 10:02 UTC, gerseystelmach submitted a review, later dismissed

2021-04-21 14:32 UTC, sblondeau requested changes

2021-04-21 14:32 UTC, sblondeau commented on src/Model/AdminBoardManager.php
> +    public function insert(array $boardMember)
hum ça doit etre delete et pas insert que je devrais avoir là ? :o

2021-04-21 15:27 UTC, maxime-guichard approved these changes

2021-04-21 15:32 UTC, eguesbaya submitted a review, later dismissed

2021-04-22 07:21 UTC, sblondeau approved these changes

2021-04-22 07:57 UTC, maxime-guichard submitted a review, later dismissed

2021-04-22 07:57 UTC, eguesbaya approved these changes
Board table re-created. all good

2021-04-22 08:35 UTC, gerseystelmach approved these changes

2021-04-22 08:50 UTC, gerseystelmach approved these changes

2021-04-22 08:50 UTC, maxime-guichard approved these changes

2021-04-22 09:11 UTC, merged