S02US07_editAdminCA
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #78
Opened 2021-04-20 15:15 UTC by glochlainn

2021-04-21 07:42 UTC, maxime-guichard submitted a review, later dismissed

2021-04-21 10:03 UTC, gerseystelmach submitted a review, later dismissed

2021-04-21 14:36 UTC, sblondeau requested changes

2021-04-21 14:36 UTC, sblondeau commented on src/Controller/AdminBoardController.php
> +            $errorsEmpty = $this->validateEmpty($boardMember);
meme remarque sur la gestion des erreurs => array_merge

2021-04-21 14:36 UTC, sblondeau commented on src/View/Admin/Board/edit.html.twig
> +			<h1 class="text-center h1">Editer un membre du CA</h1>
**É**diter (accent sur la majuscule)

2021-04-21 14:36 UTC, sblondeau commented on src/View/admin_layout.html.twig
> +<!doctype html>
je préfèrerais un système d'admin à 3 niveaux
```
layout.html.twig 
  layout_admin.html.twig  extends layout
    admin/boadrindex.html.twig extends layout_admin
```
ça éviterait de répéter du code similaire entre layout et layout_admin

2021-04-21 15:27 UTC, maxime-guichard submitted a review, later dismissed

2021-04-21 15:33 UTC, eguesbaya approved these changes

2021-04-21 15:34 UTC, eguesbaya submitted a review, later dismissed

2021-04-22 07:25 UTC, sblondeau requested changes

2021-04-22 07:25 UTC, sblondeau commented on src/Controller/AdminBoardController.php
> +    private const FIRSTNAMELENGTH = 80;
FIRSTNAME_LENGTH  (les mots séparés par des undescores quand tu écrits en majuscule)

2021-04-22 08:17 UTC, maxime-guichard approved these changes

2021-04-22 08:19 UTC, eguesbaya submitted a review, later dismissed
data validations in. all good

2021-04-22 08:24 UTC, sblondeau approved these changes

2021-04-22 08:38 UTC, maxime-guichard approved these changes

2021-04-22 08:49 UTC, gerseystelmach submitted a review, later dismissed

2021-04-22 08:49 UTC, maxime-guichard approved these changes

2021-04-22 09:13 UTC, maxime-guichard approved these changes

2021-04-22 09:14 UTC, eguesbaya approved these changes
good

2021-04-22 09:16 UTC, merged