S02US15 Creation of the Add Event Page (form + form validation + model for save events on DB)
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #79
Opened 2021-04-21 07:43 UTC by gerseystelmach

2021-04-21 07:48 UTC, glochlainn approved these changes

2021-04-21 07:53 UTC, eguesbaya submitted a review, later dismissed
all good

2021-04-21 10:04 UTC, glochlainn submitted a review, later dismissed

2021-04-21 15:24 UTC, maxime-guichard approved these changes

2021-04-21 15:35 UTC, eguesbaya approved these changes

2021-04-21 15:39 UTC, eguesbaya submitted a review, later dismissed

2021-04-22 07:50 UTC, sblondeau requested changes
tu as beaucoup de fichiers qui sont similaires à l'autre PR et qui ne devraient pas forcément être là... car les erreurs sur la 1ere PR sont à nouveau ici...
nettoie un peu, garde que les fichiers sur le add (par ex pas besoin de la favicon sur cette US)

2021-04-22 07:50 UTC, sblondeau commented on public/assets/css/adminEvents.css
> +@import 'style.css';
tu ne devrais pas importer style.css ici.
La feuille style doit etre appelée via une balise link dans ton layout.html.twig

2021-04-22 07:50 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +    public function index(): string
on ne devrait pas avoir ce code ici vu que tu fais que le add

2021-04-22 07:50 UTC, sblondeau commented on src/Controller/AdminEventController.php
> +            $errorsDateValue = $this->validateDateValue($event);
j'ai expliqué à Lochlainn, voit avec lui pour faire un array_merge ici plutot pour avoir qu'un seul tableau array

2021-04-22 07:50 UTC, sblondeau commented on src/View/Admin/Event/_form.html.twig
> +		<input type="text" value="{{- event.name -}}" class="form-control" id="name" name="name" placeholder="Ex: Voyage à Nice" required>
tu n'as pas a utiliser les "-" sur "{{-" dans ce cas, les tirets sont juste dans le cas ou y a des espaces blancs à enlever, mais là dans un attribut c'est pas nécessaire

2021-04-22 07:50 UTC, sblondeau commented on temps_des_loisirs_events.sql
> +-- SQL Dump
meme remarque sur le fichier que dans l'autre PR

2021-04-22 10:16 UTC, maxime-guichard approved these changes

2021-04-22 14:54 UTC, glochlainn submitted a review, later dismissed

2021-04-22 15:40 UTC, maxime-guichard approved these changes

2021-04-22 15:43 UTC, eguesbaya approved these changes

2021-04-22 19:26 UTC, sblondeau approved these changes

2021-04-22 19:26 UTC, merged