S02US11 - Edit Events
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #80
Opened 2021-04-21 13:41 UTC by gerseystelmach

Creation of the functionality to edit the events (model, controller, edit page).

2021-04-21 15:25 UTC, maxime-guichard submitted a review, later dismissed

2021-04-21 15:28 UTC, glochlainn submitted a review, later dismissed

2021-04-22 10:26 UTC, eguesbaya submitted a review, later dismissed
conflicts solved. all good

2021-04-22 15:01 UTC, sblondeau requested changes

2021-04-22 15:01 UTC, sblondeau commented on src/View/Admin/Event/_form.html.twig
> +	{% if errorsEmptyLength is not null %}
attention tu as fais ton array_merge donc tu n'envoies plus errorsEmptyLength et errorsDateValue  mais plus qu'un seul tableau errors

2021-04-22 15:01 UTC, sblondeau commented on src/View/Admin/Event/_form.html.twig
> +		<input type="text" value="{{- event.name -}}" class="form-control" id="name" name="name" placeholder="Ex: Voyage à Nice" required>
enlève tous les tirets autour des tes {{ }}, ils ne servent à rien ici

2021-04-23 07:10 UTC, maxime-guichard approved these changes

2021-04-23 07:12 UTC, eguesbaya approved these changes

2021-04-23 07:55 UTC, sblondeau commented
Ne passe pas github action (attention à ne pas forcer si tu as une erreur avec grumphp car tu la retrouveras sur github actions

2021-04-23 08:35 UTC, eguesbaya approved these changes

2021-04-23 08:36 UTC, eguesbaya approved these changes

2021-04-23 09:06 UTC, closed without merging