S02 us10 admin info
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #82
Opened 2021-04-21 20:01 UTC by maxime-guichard

Création de la view admin gérant les infos

2021-04-22 13:39 UTC, glochlainn submitted a review, later dismissed

2021-04-22 13:40 UTC, eguesbaya approved these changes

2021-04-22 15:06 UTC, sblondeau requested changes

2021-04-22 15:06 UTC, sblondeau commented on src/View/Admin/Information/index.html.twig
> +		<footer class="admin-footer d-flex justify-content-center flex-md-row flex-column mt-lg-5 mt-3">
ce "footer" serait plutot une autre US, à ajouter au layout coté admin.
Si tu veux juste faire un lien de retour à la page d'accueil de l'admin, je le mettrais pas ici, le footer devrait etre sous la balise  main et pas à l'intérieur, mais mettez vous d'accord sur ça pour que ça soit cohérent d'une page admin à l'autre

2021-04-23 08:08 UTC, glochlainn approved these changes

2021-04-23 08:08 UTC, gerseystelmach submitted a review, later dismissed

2021-04-23 08:39 UTC, sblondeau requested changes

2021-04-23 08:39 UTC, sblondeau commented on temps_des_loisirs.sql
> +<<<<<<< HEAD
attention un HEAD qui traine, mauvaise resolution de conflit

2021-04-23 08:39 UTC, sblondeau commented on temps_des_loisirs.sql
> +>>>>>>> 7b9c5e0919ce101d20123df031f5c1f1dfdd7ce7
et là aussi

2021-04-23 08:39 UTC, sblondeau commented on src/View/Admin/Information/index.html.twig
> +				{% if information.type == 'Avertissement' %}
là en fait tu répètes 3 fois ton code pour juste modifier une classe 
ideaelment, il faudrait que la valeur de informaion.type soit 'warning', ou danger ou d'autre classe que tu veux et dans ton code tu aurait directement des classes text-{{information.type}} qui s'afficheraient donc direct comme tu le veux avec beaucoup moins de répétitions

2021-04-23 12:54 UTC, eguesbaya approved these changes
Joli

2021-04-23 14:29 UTC, gerseystelmach approved these changes

2021-04-25 22:35 UTC, sblondeau approved these changes

2021-04-25 22:37 UTC, merged