S02 us13 admin activities add
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #87
Opened 2021-04-21 20:32 UTC by eguesbaya

Adding new activities

2021-04-21 20:33 UTC, maxime-guichard approved these changes

2021-04-21 21:44 UTC, glochlainn approved these changes

2021-04-22 09:14 UTC, glochlainn submitted a review, later dismissed

2021-04-22 09:14 UTC, maxime-guichard submitted a review, later dismissed

2021-04-22 09:22 UTC, sblondeau requested changes

2021-04-22 09:22 UTC, sblondeau commented on src/Model/ActivityManager.php
> +    public function update(array $item): bool
ne doit pas etre ici, ton US c'est juste l'add

2021-04-22 10:07 UTC, eguesbaya commented on src/Model/ActivityManager.php
> +    public function update(array $item): bool
fixed. updated with dev

2021-04-22 10:09 UTC, maxime-guichard submitted a review, later dismissed

2021-04-22 10:16 UTC, gerseystelmach approved these changes

2021-04-22 15:11 UTC, sblondeau requested changes

2021-04-22 15:11 UTC, sblondeau commented on src/Controller/AdminActivityController.php
> +        if (empty($activities['weekday'])) {
par contre tu ne vérifies jamais que weekday est bien un des 7 jours de la semaines (et que le user aurait pas modifié la value dans le bouton radio pour mettre n'importe quoi) 
ce qui pourrait etre intéressant, c'est que tu fasses une constantes DAYS avec un tableau de tes 7 jours.
tu t'en sers ici avec un in_array pour faire une vérificaiton
ET 
tu envoies ce tableau à ta vue. Dans ta vue tu boucles dessus pour construire dynamiquement tes radio button plutot que de répéter 7 fois le code HTML

2021-04-22 15:11 UTC, sblondeau commented on src/View/Components/_formAdminActivity.twig
> +                        <div class="form-check form-check-inline">
comme évoqué plus haut, ici tu ferais une boucles sur tes days et tu pourrais avoir moins de code pour construire tes 7 radio buttons

2021-04-22 15:44 UTC, gerseystelmach submitted a review, later dismissed

2021-04-23 08:35 UTC, glochlainn approved these changes

2021-04-23 08:36 UTC, maxime-guichard approved these changes

2021-04-23 08:46 UTC, sblondeau approved these changes

2021-04-23 08:46 UTC, merged

2021-04-23 08:52 UTC, eguesbaya commented on src/Controller/AdminActivityController.php
> +        if (empty($activities['weekday'])) {
Done

2021-04-23 08:52 UTC, eguesbaya commented on src/View/Components/_formAdminActivity.twig
> +                        <div class="form-check form-check-inline">
Done