S02 us12 admin activities delete
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #88
Opened 2021-04-21 21:08 UTC by eguesbaya

Deleting activities

2021-04-21 21:43 UTC, glochlainn approved these changes

2021-04-22 07:53 UTC, maxime-guichard approved these changes

2021-04-22 09:31 UTC, sblondeau requested changes
trop de chose dans les fichiers, je dois avoir que tu delete pas de l'index

2021-04-22 09:58 UTC, glochlainn approved these changes

2021-04-22 09:58 UTC, maxime-guichard approved these changes

2021-04-22 15:12 UTC, sblondeau approved these changes

2021-04-22 15:12 UTC, merged