FIX : Footer Layout Admin
WildCodeSchool/orleans-php-202103-project-tempsloisirs pull request #97
Opened 2021-04-23 07:53 UTC by glochlainn

2021-04-23 07:53 UTC, maxime-guichard submitted a review, later dismissed

2021-04-23 07:59 UTC, eguesbaya submitted a review, later dismissed
Est-ce que tu peux mettre le lien /Admin/home dans le bouton "Retour à l'accueil admin" please

2021-04-23 08:08 UTC, maxime-guichard approved these changes

2021-04-23 08:09 UTC, gerseystelmach submitted a review, later dismissed

2021-04-23 08:24 UTC, maxime-guichard approved these changes

2021-04-23 08:25 UTC, eguesbaya submitted a review, later dismissed

2021-04-26 07:07 UTC, sblondeau requested changes

2021-04-26 07:07 UTC, sblondeau commented on src/View/layoutAdmin.html.twig
> +<!doctype html>
il faudrait plutot que le layoutAdmin étende layout.html.twig, ça éviterait de répéter tout le code html commun 
de plus, ingégrer la navbar admin dans ce fichier directemetn serait sans doute intéressant pour ne pas avoir à la rajouter sur toutes les vues admin

2021-04-27 13:25 UTC, maxime-guichard approved these changes

2021-04-27 13:45 UTC, gerseystelmach approved these changes

2021-04-27 14:13 UTC, sblondeau approved these changes

2021-04-27 14:14 UTC, merged